# Generated by Django 3.0 on 2021-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_property_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verfied',
            field=models.BooleanField(default=False),
        ),
    ]
