# Generated by Django 3.0 on 2021-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_verfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.BooleanField(default=False),
        ),
    ]
