# Generated by Django 3.0 on 2022-01-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20220108_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='buyer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Property'),
        ),
    ]
