# Generated by Django 3.0 on 2022-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Tenament', 'Tenament'), ('Bungalow', 'Bungalow'), ('villas', 'villas')], max_length=100),
        ),
    ]
