# Generated by Django 3.0 on 2022-01-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220125_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_sub_type',
            field=models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6 BHK', '6 BHK')], max_length=100),
        ),
    ]
