# Generated by Django 3.0 on 2022-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20220125_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=models.CharField(choices=[('Maninagar', 'Maninagar'), ('Memnagar', 'Memnagar'), ('Bopal', 'Bopal'), ('Iskon', 'Iskon'), ('Gota', 'Gota'), ('Vaishnodevi', 'Vaishnodevi'), ('Naranpura', 'Naranpura'), ('Sola', 'Sola'), ('Thaltej', 'Thaltej'), ('Sarkej', 'Sarkej'), ('Shilaj', 'Shilaj'), ('Navrangpura', 'Navrangpura'), ('Gurukul', 'Gurukul'), ('Juhapura', 'Juhapura'), ('Ambavadi', 'Ambavadi'), ('Shivranjani', 'Shivranjani'), ('Ghodasar', 'Ghodasar'), ('Vastrapur', 'Vastrapur'), ('Vastral', 'Vastral'), ('K.K Nagar', 'K.K Nagar')], default='Bopal', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_sub_type',
            field=models.CharField(choices=[('1 BHK', '1 BHK'), ('2 BHK', '2 BHK'), ('3 BHK', '3 BHK'), ('4 BHK', '4 BHK'), ('5 BHK', '5 BHK'), ('6 BHK', '6 BHK'), ('7 BHK', '7 BHK'), ('8 BHK', '8 BHK')], max_length=100),
        ),
    ]
